import { useQuery } from '@tanstack/react-query'
import { IonBadge, IonCard, IonCardContent, IonContent, IonHeader, IonInput, IonList, IonPage, IonRefresher, IonRefresherContent, IonSearchbar, IonSelect, IonSelectOption, IonTitle, IonToolbar } from '@ionic/react'
import { useState } from 'react'
import { Empty, ErrorState, LoadingCards } from '../components'
import { api } from '../lib/api'
import { displayDateTime } from '../lib/time'
import type { Booking, Page } from '../types'
export default function Bookings() {
  const [search,setSearch]=useState('');const[status,setStatus]=useState('');const[from,setFrom]=useState('');const[to,setTo]=useState('');const params=new URLSearchParams();if(search)params.set('search',search);if(status)params.set('status',status);if(from)params.set('date_from',from);if(to)params.set('date_to',to); const query=useQuery({queryKey:['bookings',search,status,from,to],queryFn:()=>api<Page<Booking>>(`/bookings?${params}`)})
  return <IonPage><IonHeader><IonToolbar><IonTitle>Passenger bookings</IonTitle></IonToolbar><IonToolbar><IonSearchbar debounce={350} value={search} onIonInput={e=>setSearch(e.detail.value||'')}/><IonSelect aria-label="Status" placeholder="All statuses" value={status} onIonChange={e=>setStatus(e.detail.value)}><IonSelectOption value="">All statuses</IonSelectOption><IonSelectOption value="CONFIRMED">Confirmed</IonSelectOption><IonSelectOption value="COMPLETED">Completed</IonSelectOption></IonSelect><div className="date-filters"><IonInput type="date" aria-label="From date" value={from} onIonInput={e=>setFrom(e.detail.value!)}/><IonInput type="date" aria-label="To date" value={to} onIonInput={e=>setTo(e.detail.value!)}/></div></IonToolbar></IonHeader><IonContent><IonRefresher slot="fixed" onIonRefresh={e=>query.refetch().finally(()=>e.detail.complete())}><IonRefresherContent/></IonRefresher>{query.isLoading?<LoadingCards/>:query.error?<ErrorState error={query.error} retry={()=>query.refetch()}/>:!query.data?.results.length?<Empty title="No passenger bookings"/>:<IonList lines="none">{query.data.results.map(b=><IonCard key={b.id}><IonCardContent><div className="card-title">{b.customer_name}<IonBadge>{b.status}</IonBadge></div><p>{b.route_name}: {b.start_stop.name} → {b.end_stop.name}</p><p>{b.seats} seat{b.seats===1?'':'s'} · {displayDateTime(b.departure_time)}</p><p><a href={`tel:${b.customer_phone}`}>{b.customer_phone}</a></p></IonCardContent></IonCard>)}</IonList>}</IonContent></IonPage>
}
