import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { IonBadge, IonButton, IonCard, IonCardContent, IonContent, IonHeader, IonInput, IonList, IonModal, IonPage, IonRefresher, IonRefresherContent, IonSearchbar, IonSelect, IonSelectOption, IonTitle, IonToolbar, useIonAlert } from '@ionic/react'
import { useState } from 'react'
import { Empty, ErrorState, LoadingCards } from '../components'
import { api } from '../lib/api'
import { displayDateTime } from '../lib/time'
import type { CabBooking, Car, Page } from '../types'
export default function CabBookings(){
 const qc=useQueryClient(); const [status,setStatus]=useState('BOOKED');const[search,setSearch]=useState('');const[from,setFrom]=useState('');const[to,setTo]=useState(''); const [selected,setSelected]=useState<CabBooking|null>(null); const [form,setForm]=useState({car:'',driver_name:'',driver_no:''}); const [alert]=useIonAlert();const params=new URLSearchParams();if(status)params.set('status',status);if(search)params.set('search',search);if(from)params.set('date_from',from);if(to)params.set('date_to',to)
 const query=useQuery({queryKey:['cab-bookings',status,search,from,to],queryFn:()=>api<Page<CabBooking>>(`/cab-bookings?${params}`)}); const cars=useQuery({queryKey:['cars'],queryFn:()=>api<Page<Car>>('/cars?page_size=100')})
 const confirm=useMutation({mutationFn:()=>api<CabBooking>(`/cab-bookings/${selected!.id}/confirm`,{method:'POST',body:JSON.stringify(form)}),onSuccess:()=>{qc.invalidateQueries({queryKey:['cab-bookings']});setSelected(null)}})
 return <IonPage><IonHeader><IonToolbar><IonTitle>Cab bookings</IonTitle></IonToolbar><IonToolbar><IonSearchbar debounce={350} placeholder="Customer or location" value={search} onIonInput={e=>setSearch(e.detail.value||'')}/><IonSelect aria-label="Status" value={status} onIonChange={e=>setStatus(e.detail.value)}><IonSelectOption value="">All statuses</IonSelectOption>{['BOOKED','CONFIRMED','CANCELLED'].map(x=><IonSelectOption key={x}>{x}</IonSelectOption>)}</IonSelect><div className="date-filters"><IonInput type="date" aria-label="From date" value={from} onIonInput={e=>setFrom(e.detail.value!)}/><IonInput type="date" aria-label="To date" value={to} onIonInput={e=>setTo(e.detail.value!)}/></div></IonToolbar></IonHeader><IonContent><IonRefresher slot="fixed" onIonRefresh={e=>query.refetch().finally(()=>e.detail.complete())}><IonRefresherContent/></IonRefresher>{query.isLoading?<LoadingCards/>:query.error?<ErrorState error={query.error} retry={()=>query.refetch()}/>:!query.data?.results.length?<Empty title="No cab requests"/>:<IonList lines="none">{query.data.results.map(b=><IonCard key={b.id} button={b.status==='BOOKED'} onClick={()=>b.status==='BOOKED'&&setSelected(b)}><IonCardContent><div className="card-title">#{b.id} · {b.customer_name}<IonBadge color={b.status==='BOOKED'?'warning':'success'}>{b.status}</IonBadge></div><p>{b.pickup_location} → {b.dropoff_location}</p><p>{displayDateTime(b.pickup_time)} · {b.people_count} people</p>{b.car&&<p>{b.car.name} ({b.car.license_plate}) · {b.driver_name}</p>}</IonCardContent></IonCard>)}</IonList>}
 <IonModal isOpen={!!selected} onDidDismiss={()=>setSelected(null)}><IonHeader><IonToolbar><IonTitle>Confirm request #{selected?.id}</IonTitle><IonButton fill="clear" slot="end" onClick={()=>setSelected(null)}>Close</IonButton></IonToolbar></IonHeader><IonContent className="ion-padding"><p>{selected?.pickup_location} → {selected?.dropoff_location}</p><IonSelect label="Car" labelPlacement="stacked" fill="outline" value={form.car} onIonChange={e=>setForm(v=>({...v,car:e.detail.value}))}>{cars.data?.results.map(c=><IonSelectOption key={c.id} value={c.id}>{c.name} · {c.license_plate}</IonSelectOption>)}</IonSelect><IonInput label="Driver name" labelPlacement="stacked" fill="outline" value={form.driver_name} onIonInput={e=>setForm(v=>({...v,driver_name:e.detail.value!}))}/><IonInput type="tel" label="Driver phone" labelPlacement="stacked" fill="outline" value={form.driver_no} onIonInput={e=>setForm(v=>({...v,driver_no:e.detail.value!}))}/>{confirm.error&&<p className="error">{confirm.error.message}</p>}<IonButton expand="block" disabled={!form.car||!form.driver_name||!form.driver_no||confirm.isPending} onClick={()=>alert({header:'Confirm this cab booking?',message:'Other vendors will no longer be able to claim it.',buttons:['Cancel',{text:'Confirm',handler:()=>confirm.mutate()}]})}>Assign and confirm</IonButton></IonContent></IonModal>
 </IonContent></IonPage>
}
