import { Browser } from '@capacitor/browser'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { IonButton, IonCard, IonCardContent, IonContent, IonHeader, IonInput, IonItem, IonLabel, IonList, IonModal, IonPage, IonSegment, IonSegmentButton, IonSelect, IonSelectOption, IonTitle, IonToolbar } from '@ionic/react'
import { useState } from 'react'
import { useAuth } from '../auth'
import { Empty, ErrorState, LoadingCards } from '../components'
import { api } from '../lib/api'
import type { Car, Page, Route, Stop } from '../types'

type Section='routes'|'stops'|'cars'|'settings'
export default function Manage(){const[section,setSection]=useState<Section>('routes');return <IonPage><IonHeader><IonToolbar><IonTitle>Manage</IonTitle></IonToolbar><IonToolbar><IonSegment scrollable value={section} onIonChange={e=>setSection(e.detail.value as Section)}>{['routes','stops','cars','settings'].map(s=><IonSegmentButton key={s} value={s}><IonLabel>{s}</IonLabel></IonSegmentButton>)}</IonSegment></IonToolbar></IonHeader><IonContent>{section==='routes'?<Routes/>:section==='stops'?<Stops/>:section==='cars'?<Cars/>:<Settings/>}</IonContent></IonPage>}

function Stops(){const qc=useQueryClient();const[name,setName]=useState('');const[description,setDescription]=useState('');const q=useQuery({queryKey:['stops'],queryFn:()=>api<Page<Stop>>('/stops?page_size=100')});const add=useMutation({mutationFn:()=>api<Stop>('/stops',{method:'POST',body:JSON.stringify({name,description})}),onSuccess:()=>{setName('');setDescription('');qc.invalidateQueries({queryKey:['stops']})}});return <div className="manage"><h2>Stops</h2><IonInput label="Name" labelPlacement="stacked" fill="outline" value={name} onIonInput={e=>setName(e.detail.value!)}/><IonInput label="Description" labelPlacement="stacked" fill="outline" value={description} onIonInput={e=>setDescription(e.detail.value!)}/>{add.error&&<p className="error">{add.error.message}</p>}<IonButton expand="block" disabled={!name||add.isPending} onClick={()=>add.mutate()}>Add stop</IonButton>{q.isLoading?<LoadingCards/>:q.error?<ErrorState error={q.error} retry={()=>q.refetch()}/>:<IonList>{q.data?.results.map(s=><IonItem key={s.id}><IonLabel>{s.name}<p>{s.description}</p></IonLabel></IonItem>)}</IonList>}</div>}

function Cars(){const qc=useQueryClient();const[name,setName]=useState('');const[license_plate,setPlate]=useState('');const q=useQuery({queryKey:['cars'],queryFn:()=>api<Page<Car>>('/cars?page_size=100')});const add=useMutation({mutationFn:()=>api<Car>('/cars',{method:'POST',body:JSON.stringify({name,license_plate})}),onSuccess:()=>{setName('');setPlate('');qc.invalidateQueries({queryKey:['cars']})}});return <div className="manage"><h2>Cars</h2><IonInput label="Car name" labelPlacement="stacked" fill="outline" value={name} onIonInput={e=>setName(e.detail.value!)}/><IonInput label="License plate" labelPlacement="stacked" fill="outline" value={license_plate} onIonInput={e=>setPlate(e.detail.value!)}/>{add.error&&<p className="error">{add.error.message}</p>}<IonButton expand="block" disabled={!name||!license_plate||add.isPending} onClick={()=>add.mutate()}>Add car</IonButton>{q.isLoading?<LoadingCards/>:<IonList>{q.data?.results.map(c=><IonItem key={c.id}><IonLabel>{c.name}<p>{c.license_plate}</p></IonLabel></IonItem>)}</IonList>}</div>}

type StopRow={stop_id:number|string;order:number;minutes_from_previous_stop:number;distance_from_previous_stop:number}
function Routes(){const qc=useQueryClient();const[selected,setSelected]=useState<Route|null|undefined>(undefined);const[name,setName]=useState('');const[description,setDescription]=useState('');const[rows,setRows]=useState<StopRow[]>([{stop_id:'',order:1,minutes_from_previous_stop:0,distance_from_previous_stop:0},{stop_id:'',order:2,minutes_from_previous_stop:1,distance_from_previous_stop:1}]);const q=useQuery({queryKey:['routes'],queryFn:()=>api<Page<Route>>('/routes?page_size=100')});const stops=useQuery({queryKey:['stops'],queryFn:()=>api<Page<Stop>>('/stops?page_size=100')});const save=useMutation({mutationFn:()=>api<Route>(selected?.id?`/routes/${selected.id}`:'/routes',{method:selected?.id?'PATCH':'POST',body:JSON.stringify({name,description,stops:rows})}),onSuccess:()=>{qc.invalidateQueries({queryKey:['routes']});setSelected(undefined)}})
const open=(route?:Route)=>{setSelected(route||null);setName(route?.name||'');setDescription(route?.description||'');setRows(route?.route_stops.map(x=>({stop_id:x.stop_id,order:x.order,minutes_from_previous_stop:x.minutes_from_previous_stop,distance_from_previous_stop:x.distance_from_previous_stop}))||[{stop_id:'',order:1,minutes_from_previous_stop:0,distance_from_previous_stop:0},{stop_id:'',order:2,minutes_from_previous_stop:1,distance_from_previous_stop:1}])};const change=(i:number,key:keyof StopRow,value:string|number)=>setRows(v=>v.map((r,j)=>j===i?{...r,[key]:value}:r));return <div className="manage"><div className="section-title"><h2>Routes</h2><IonButton onClick={()=>open()}>New route</IonButton></div>{q.isLoading?<LoadingCards/>:q.error?<ErrorState error={q.error} retry={()=>q.refetch()}/>:!q.data?.results.length?<Empty title="No routes"/>:<IonList lines="none">{q.data.results.map(r=><IonCard button key={r.id} onClick={()=>open(r)}><IonCardContent><div className="card-title">{r.name}<span>{r.stop_count} stops</span></div><p>{r.route_stops.map(x=>x.stop.name).join(' → ')}</p></IonCardContent></IonCard>)}</IonList>}
<IonModal isOpen={selected!==undefined} onDidDismiss={()=>setSelected(undefined)}><IonHeader><IonToolbar><IonTitle>{selected?.id?'Edit route':'New route'}</IonTitle><IonButton fill="clear" slot="end" onClick={()=>setSelected(undefined)}>Close</IonButton></IonToolbar></IonHeader><IonContent className="ion-padding"><IonInput label="Route name" labelPlacement="stacked" fill="outline" value={name} onIonInput={e=>setName(e.detail.value!)}/><IonInput label="Description" labelPlacement="stacked" fill="outline" value={description} onIonInput={e=>setDescription(e.detail.value!)}/><h2>Ordered stops</h2>{rows.map((row,i)=><IonCard key={i}><IonCardContent><div className="card-title">Stop {i+1}{rows.length>2&&<IonButton size="small" fill="clear" color="danger" onClick={()=>setRows(v=>v.filter((_,j)=>j!==i).map((x,j)=>({...x,order:j+1})))}>Remove</IonButton>}</div><IonSelect label="Stop" labelPlacement="stacked" fill="outline" value={row.stop_id} onIonChange={e=>change(i,'stop_id',e.detail.value)}>{stops.data?.results.map(s=><IonSelectOption key={s.id} value={s.id}>{s.name}</IonSelectOption>)}</IonSelect><IonInput disabled={i===0} type="number" min={i?1:0} label="Minutes from previous" labelPlacement="stacked" fill="outline" value={row.minutes_from_previous_stop} onIonInput={e=>change(i,'minutes_from_previous_stop',Number(e.detail.value))}/><IonInput disabled={i===0} type="number" min={i?1:0} label="Kilometres from previous" labelPlacement="stacked" fill="outline" value={row.distance_from_previous_stop} onIonInput={e=>change(i,'distance_from_previous_stop',Number(e.detail.value))}/></IonCardContent></IonCard>)}<IonButton fill="outline" expand="block" onClick={()=>setRows(v=>[...v,{stop_id:'',order:v.length+1,minutes_from_previous_stop:1,distance_from_previous_stop:1}])}>Add stop</IonButton>{save.error&&<p className="error">{save.error.message}</p>}<IonButton expand="block" disabled={!name||rows.some(r=>!r.stop_id)||save.isPending} onClick={()=>save.mutate()}>Save route</IonButton></IonContent></IonModal></div>}

function Settings(){const{vendor,logout}=useAuth();return <div className="manage"><h2>{vendor?.company_name}</h2><p>@{vendor?.username}</p><IonButton expand="block" fill="outline" onClick={()=>Browser.open({url:import.meta.env.VITE_PRIVACY_POLICY_URL||'https://cab.bits-oasis.org/privacy-policy/'})}>Privacy policy</IonButton><IonButton expand="block" color="danger" fill="outline" onClick={()=>logout()}>Log out</IonButton><p className="version">Ridezy Vendor 1.0.0</p></div>}
