import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { IonBadge, IonButton, IonCard, IonCardContent, IonContent, IonFab, IonFabButton, IonHeader, IonIcon, IonInput, IonItem, IonLabel, IonList, IonModal, IonPage, IonRefresher, IonRefresherContent, IonSearchbar, IonSelect, IonSelectOption, IonTitle, IonToolbar, useIonAlert } from '@ionic/react'
import { add, calendarOutline } from 'ionicons/icons'
import { useState } from 'react'
import { api, ApiError } from '../lib/api'
import { displayDateTime, isoToLocalInput, localInputToIso } from '../lib/time'
import type { Page, Route, Trip, TripStatus } from '../types'
import { Empty, ErrorState, LoadingCards } from '../components'

type TripForm = { route: number | ''; departure_time: string; vehicle_capacity: number; cost_per_km: string; status: TripStatus }
const blank = (): TripForm => ({ route: '', departure_time: isoToLocalInput(new Date().toISOString()), vehicle_capacity: 4, cost_per_km: '', status: 'SCHEDULED' })
export default function Trips() {
  const qc = useQueryClient(); const [status, setStatus] = useState(''); const [search,setSearch]=useState(''); const [dateFrom,setDateFrom]=useState(''); const [dateTo,setDateTo]=useState(''); const [editing, setEditing] = useState<Trip | null>(null); const [form, setForm] = useState<TripForm>(blank()); const [bulk, setBulk] = useState(false); const [presentAlert] = useIonAlert()
  const params=new URLSearchParams(); if(status)params.set('status',status);if(search)params.set('search',search);if(dateFrom)params.set('date_from',dateFrom);if(dateTo)params.set('date_to',dateTo)
  const trips = useQuery({ queryKey: ['trips', status,search,dateFrom,dateTo], queryFn: () => api<Page<Trip>>(`/trips?${params}`) })
  const routes = useQuery({ queryKey: ['routes'], queryFn: () => api<Page<Route>>('/routes?page_size=100') })
  const save = useMutation({ mutationFn: () => api<Trip>(editing ? `/trips/${editing.id}` : '/trips', { method: editing ? 'PATCH' : 'POST', body: JSON.stringify({ ...form, departure_time: localInputToIso(form.departure_time) }) }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['trips'] }); setEditing(null); setForm(blank()) } })
  const open = (trip?: Trip) => { if (trip) { setEditing(trip); setForm({ route: trip.route, departure_time: isoToLocalInput(trip.departure_time), vehicle_capacity: trip.vehicle_capacity, cost_per_km: trip.cost_per_km, status: trip.status }) } else { setEditing({} as Trip); setForm(blank()) } }
  const close = () => setEditing(null)
  return <IonPage><IonHeader><IonToolbar><IonTitle>Trips</IonTitle><IonButton slot="end" fill="clear" onClick={() => setBulk(true)}><IonIcon icon={calendarOutline}/></IonButton></IonToolbar><IonToolbar><IonSearchbar debounce={350} placeholder="Search routes" value={search} onIonInput={e=>setSearch(e.detail.value||'')}/><IonSelect aria-label="Filter status" interface="popover" placeholder="All statuses" value={status} onIonChange={e => setStatus(e.detail.value)}><IonSelectOption value="">All statuses</IonSelectOption>{['SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED'].map(x => <IonSelectOption key={x}>{x}</IonSelectOption>)}</IonSelect><div className="date-filters"><IonInput type="date" aria-label="From date" value={dateFrom} onIonInput={e=>setDateFrom(e.detail.value!)}/><IonInput type="date" aria-label="To date" value={dateTo} onIonInput={e=>setDateTo(e.detail.value!)}/></div></IonToolbar></IonHeader><IonContent>
    <IonRefresher slot="fixed" onIonRefresh={e => trips.refetch().finally(() => e.detail.complete())}><IonRefresherContent/></IonRefresher>
    {trips.isLoading ? <LoadingCards/> : trips.error ? <ErrorState error={trips.error} retry={() => trips.refetch()}/> : !trips.data?.results.length ? <Empty title="No trips found">Create your first scheduled trip.</Empty> : <IonList lines="none">{trips.data.results.map(t => <IonCard button key={t.id} onClick={() => open(t)}><IonCardContent><div className="card-title">{t.route_name}<IonBadge color={t.status === 'CANCELLED' ? 'danger' : 'primary'}>{t.status.replace('_',' ')}</IonBadge></div><p>{displayDateTime(t.departure_time)}</p><p>{t.booked_seats}/{t.vehicle_capacity} seats booked · ₹{t.cost_per_km}</p></IonCardContent></IonCard>)}</IonList>}
    <IonFab vertical="bottom" horizontal="end" slot="fixed"><IonFabButton aria-label="Create trip" onClick={() => open()}><IonIcon icon={add}/></IonFabButton></IonFab>
    <IonModal isOpen={!!editing} onDidDismiss={close}><IonHeader><IonToolbar><IonTitle>{editing?.id ? 'Edit trip' : 'New trip'}</IonTitle><IonButton slot="end" fill="clear" onClick={close}>Close</IonButton></IonToolbar></IonHeader><IonContent className="ion-padding"><form onSubmit={e => { e.preventDefault(); presentAlert({ header: editing?.id ? 'Save trip changes?' : 'Create this trip?', buttons: ['Cancel', { text: 'Confirm', handler: () => save.mutate() }] }) }}>
      <IonSelect label="Route" labelPlacement="stacked" fill="outline" value={form.route} onIonChange={e => setForm(v => ({...v, route: e.detail.value}))}>{routes.data?.results.map(r => <IonSelectOption key={r.id} value={r.id}>{r.name}</IonSelectOption>)}</IonSelect>
      <IonInput type="datetime-local" label="Departure (India time)" labelPlacement="stacked" fill="outline" value={form.departure_time} onIonInput={e => setForm(v => ({...v, departure_time: e.detail.value!}))}/>
      <IonInput type="number" min="1" label="Capacity" labelPlacement="stacked" fill="outline" value={form.vehicle_capacity} onIonInput={e => setForm(v => ({...v, vehicle_capacity: Number(e.detail.value)}))}/>
      <IonInput type="number" min="0.01" step="0.01" label="Price per seat" labelPlacement="stacked" fill="outline" value={form.cost_per_km} onIonInput={e => setForm(v => ({...v, cost_per_km: e.detail.value!}))}/>
      {editing?.id && <IonSelect label="Status" labelPlacement="stacked" fill="outline" value={form.status} onIonChange={e => setForm(v => ({...v, status: e.detail.value}))}>{['SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED'].map(x => <IonSelectOption key={x}>{x}</IonSelectOption>)}</IonSelect>}
      {save.error && <p className="error">{save.error.message}</p>}<IonButton expand="block" type="submit" disabled={save.isPending || !form.route}>Save trip</IonButton>
    </form>{editing?.schedule?.length ? <><h2>Schedule</h2><IonList>{editing.schedule.map(s => <IonItem key={s.route_stop_id}><IonLabel>{s.order}. {s.stop_name}<p>{displayDateTime(s.estimated_arrival_time)}</p></IonLabel></IonItem>)}</IonList></> : null}</IonContent></IonModal>
    <BulkModal open={bulk} close={() => setBulk(false)} routes={routes.data?.results || []}/>
  </IonContent></IonPage>
}

function BulkModal({ open, close, routes }: { open: boolean; close: () => void; routes: Route[] }) {
  const qc = useQueryClient(); const now = new Date(); const [data, setData] = useState({ route: '', departure_time: '09:00', month: now.getMonth()+1, year: now.getFullYear(), vehicle_capacity: 4, cost_per_km: '' })
  const mutation = useMutation({ mutationFn: () => api<{created_count:number}>('/trips/bulk', { method: 'POST', body: JSON.stringify(data) }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['trips'] }); close() } })
  return <IonModal isOpen={open} onDidDismiss={close}><IonHeader><IonToolbar><IonTitle>Create monthly trips</IonTitle><IonButton fill="clear" slot="end" onClick={close}>Close</IonButton></IonToolbar></IonHeader><IonContent className="ion-padding"><p>Creates one trip on every day of the selected month.</p><IonSelect label="Route" labelPlacement="stacked" fill="outline" value={data.route} onIonChange={e => setData(v=>({...v,route:e.detail.value}))}>{routes.map(r=><IonSelectOption key={r.id} value={r.id}>{r.name}</IonSelectOption>)}</IonSelect><IonInput type="time" label="Daily departure" labelPlacement="stacked" fill="outline" value={data.departure_time} onIonInput={e=>setData(v=>({...v,departure_time:e.detail.value!}))}/><IonInput type="number" min="1" max="12" label="Month" labelPlacement="stacked" fill="outline" value={data.month} onIonInput={e=>setData(v=>({...v,month:Number(e.detail.value)}))}/><IonInput type="number" min="2024" max="2100" label="Year" labelPlacement="stacked" fill="outline" value={data.year} onIonInput={e=>setData(v=>({...v,year:Number(e.detail.value)}))}/><IonInput type="number" min="1" label="Capacity" labelPlacement="stacked" fill="outline" value={data.vehicle_capacity} onIonInput={e=>setData(v=>({...v,vehicle_capacity:Number(e.detail.value)}))}/><IonInput type="number" min="0.01" step="0.01" label="Price per seat" labelPlacement="stacked" fill="outline" value={data.cost_per_km} onIonInput={e=>setData(v=>({...v,cost_per_km:e.detail.value!}))}/>{mutation.error && <p className="error">{mutation.error.message}</p>}<IonButton expand="block" onClick={() => mutation.mutate()} disabled={mutation.isPending || !data.route}>Create daily trips</IonButton></IonContent></IonModal>
}
